#!/bin/bash -e
DILA_PATH=$(dirname $(readlink -f $BASH_SOURCE))
export PATH=$DILA_PATH/dila-development-compose/bin:$PATH
function dila_install_requirements {
    DOCKER_COMPOSE_VERSION=1.8.0
    if dpkg --compare-versions $(docker-compose version --short 2>/dev/null || echo 0) lt $DOCKER_COMPOSE_VERSION;
    then
       DOCKER_COMPOSE_PATH=$DILA_PATH/dila-development-compose/bin/docker-compose
       echo "Installing docker compose."
       curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` >$DOCKER_COMPOSE_PATH
       chmod +x $DOCKER_COMPOSE_PATH
       if dpkg --compare-versions $(docker-compose version --short 2>/dev/null || echo 0) ne $DOCKER_COMPOSE_VERSION;
       then
           echo "Failed"
       fi
    fi
}
