dila:
  image: dila_dev_image
  links:
   - db
  ports:
   - "8089:80"
  volumes:
   - ../dila:/package/dila
db:
  image: postgres:9.6.2
  environment:
    POSTGRES_USER: dila
    POSTGRES_PASSWORD: dila
