dila:
  image: dila_dev_image
  links:
   - db
   - ldap
  ports:
   - "8089:80"
  volumes:
   - ../dila:/package/dila
db:
  image: postgres:9.6.2
  environment:
    POSTGRES_USER: dila
    POSTGRES_PASSWORD: dila
ldap:
  image: osixia/openldap:1.1.8
  volumes:
    - ../acceptance_tests/test.ldif:/scripts/test.ldif:ro
  environment:
    - LDAP_ORGANISATION="Dila"
    - LDAP_DOMAIN=example.com
    - LDAP_ADMIN_PASSWORD=admin_password
